/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;


public class AppTest {
    @Test public void testAppHasAGreeting() {
        projectzero.App classUnderTest = new projectzero.App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
