package projectzero;

import projectzero.entities.VendingMachine;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    
    public String getGreeting() {
        return "\"Hello world.\" -- Vending Machine.";
    }

    public static void main(String[] args) {
	VendingMachine vend = new VendingMachine("Le Vending Spot", "Mr. Edwards", "An arbitrary forest in Northern New England. This vending machine is comfortably tucked under a rocky alcove. 1368 A.D.");
	System.out.println(vend.toString());
        System.out.println(new App().getGreeting());
    }
}
