
package projectzero.vendingmachine;

import java.util.HashMap;
import java.util.ArrayList;

import projectzero.vendingmachine.entities.VendingMachine;
import projectzero.vendingmachine.utilities.Printing;
import projectzero.vendingmachine.utilities.Input;
import projectero.vendingmachine.utilities.Container;
import projectzero.vendingmachine.utilities.NamedContainers;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    
    public String getGreeting() {
        return "\"Hello world.\" -- Vending Machine.";
    }

    public static void main(String[] args) {
	VendingMachine vend = new VendingMachine("Le Vending Spot", "Mr. Edwards", "An arbitrary forest in Northern New England. This vending machine is comfortably tucked under a rocky alcove. 1368 A.D.");
	Input input = new Input();
	Container textInput = new Container(new ArrayList<String>());
	Container staticContent = new Container(new ArrayList<String>());
	//Container textOutput = new Container(new ArrayList<String>());
	String userInput = "";
	HashMap<String, Container> consoleContentMap = new HashMap<String, Container>();
	NamedContainers consoleContainer = new NamedContainers(50, consoleContentMap);
	
	// Add content to consoleContentMap
	consoleContentMap.put("input", textInput);
	//consoleContentMap.put("output", textOutput);
	consoleContentMap.put("staticContent", staticContent);

	staticContent.add(vend.toArrayList());
        staticContent.add(new App().getGreeting());	
	System.out.println(consoleContainer.toString());
	shell:
	while ((userInput = input.next()) != "close") {
	    switch(userInput) {
		default:
		    textInput.add("=>" + userInput);
		    System.out.println(consoleContainer.toString());
		    break;
	        case "history":
		    input.printHistory();
		    break;
	        case "exit":
		    break shell;
	    }
	}
    }
}
